PUT http://localhost:3000/api/blogs/6387c3dbeb34e4704a35b74f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inh4c3VidXh4IiwiaWQiOiI2Mzg3YWJhNmFjOGU0NDVlZWY5NGM1MGMiLCJpYXQiOjE2Njk4NDExMzB9.RrWEX9wk7tXRokFv5slqqKgQCITDxXz3oejMzuJ18jE

{
    "title": "Taerdsf",
    "author": "dsfdsaf C. Martin",
    "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
    "likes": 2
}